Class {
	#name : #AllTestFailTest,
	#superclass : #TestCase,
	#category : #'TestRunner-Tests-Utilities-Test'
}

{ #category : #tests }
AllTestFailTest >> testFail1 [
	self assert: false
]

{ #category : #tests }
AllTestFailTest >> testFail2 [
	self assert: false
]

{ #category : #tests }
AllTestFailTest >> testFail3 [
	self assert: false
]

{ #category : #tests }
AllTestFailTest >> testFail4 [
	self assert: false
]
